import { createAction } from 'redux-actions'


export const updateTrackingStatus = createAction('UPDATE_LOCATION_TRACKING_STATUS')
export const updateTrackedLeaderboard = createAction('UPDATE_TRACKED_LEADERBOARD')
export const updateTrackedEventId = createAction('UPDATE_TRACKED_EVENT_ID')
export const removeTrackedRegatta = createAction('REMOVE_TRACKED_REGATTA')
export const updateTrackedRegatta = createAction('UPDATE_TRACKED_REGATTA')
export const updateUnsentGpsFixCount = createAction('UPDATE_UNSENT_GPS_FIX_COUNT')
export const updateTrackingStatistics = createAction('UPDATE_TRACKING_STATISTICS')
export const updateLocationAccuracy = createAction('UPDATE_LOCATION_ACCURACY')
export const updateSpeedInKnots = createAction('UPDATE_SPEED_IN_KNOTS')
export const updateStartedAt = createAction('UPDATE_STARTED_AT')
export const updateHeadingInDeg = createAction('UPDATE_HEADING_IN_DEG')
export const updateDistance = createAction('UPDATE_DISTANCE')
export const updateLastWindCourse = createAction('UPDATE_WIND_COURSE')
export const updateLastWindSpeed = createAction('UPDATE_WIND_SPEED')
export const updateValidGpsFixCount = createAction('UPDATE_VALID_GPS_FIX_COUNT')
export const updateTrackingStartTimeUpdateFlag = createAction('UPDATE_TRACKING_START_TIME_UPDATED_FLAG')
export const updateStartAutoCourseStatus = createAction('UPDATE_START_AUTO_COURSE_STATUS')
