# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sap_sailing_insight' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sap_sailing_insight

  # this is very important to have!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  pod 'Firebase/Core'

  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  target 'sap_sailing_insightTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'sap_sailing_insight-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sap_sailing_insight-tvOS

  target 'sap_sailing_insight-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
  targets_to_ignore = %w(React yoga)
  installer.pods_project.targets.each do |target|
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end
  end
end
