
export default {
  defaults: {
    map: require('./img/defaults/Map.png'),
    map2: require('./img/defaults/Map2.png'),
    background_map: require('./img/tracking/TrackingMap_Background.png'),
    background_empty: require('./img/session/LooksEmpty.png'),
    background_empty_de: require('./img/session/LooksEmpty_de.png'),
    app_logo: require('./img/defaults/AppLogo.png'),
    ws_logo: require('./img/defaults/WorldSailingLogo.png'),
    sap_logo: require('./img/defaults/SAP.png'),
    attention: require('./img/new_icons/attention.png'),
  },
  header: {
    sailors: require('./img/header_sailors.png'),
    team: require('./img/team_headerimage.png'),
  },
  actions: {
    add: require('./img/new_icons/add_icon_circle.png'),
    decrease: require('./img/new_icons/minus_icon_circle.png'),
    settings: require('./img/icons/icon-settings.png'),
    recordColored: require('./img/icons/icon-start.png'), // TODO: replace
    pen: require('./img/icons/icon-edit.png'),
    penEdit: require('./img/icons/icon-pen-edit.png'),
    visibility: require('./img/icons/icon-visibility.png'),
    visibilityOff: require('./img/icons/icon-visibility-off.png'),
    help: require('./img/icons/icon-help.png'),
    arrowRight: require('./img/icons/icon-arrow-chevron-right.png'),
    arrowLeft: require('./img/icons/icon-arrow-chevron-left.png'),
    close: require('./img/icons/icon-cross.png'),
    expandLess: require('./img/icons/icon-arrow-expand-less.png'),
    expandMore: require('./img/icons/icon-arrow-expand-more.png'),
    pickImage: require('./img/new_icons/camera.png'),
    delete: require('./img/icons/icon-delete.png'),
    share: require('./img/icons/icon-open-in-new.png'),
    plus: require('./img/icons/plus.png'),
    arrowUp: require('./img/new_icons/arrow-chevron-up.png'),
    arrowDown: require('./img/new_icons/arrow-chevron-down.png'),
  },
  tabs: {
    tracking: require('./img/new_icons/tracking_icon.png'),
    account: require('./img/new_icons/account_icon.png'),
    sessions: require('./img/new_icons/sessions_icon.png'),
    inventory: require('./img/new_icons/inventory_icon.png'),
    join: require('./img/icons/icon-scan.png'),
  },
  info: {
    boat: require('./img/icons/icon-boat.png'),
    location: require('./img/icons/icon-place.png'),
    arrowUp: require('./img/icons/icon-arrow-up.png'),
    arrowDown: require('./img/icons/icon-arrow-down.png'),
    distance: require('./img/icons/icon-distance.png'),
    time: require('./img/icons/icon-watch.png'),
    maneuvers: require('./img/icons/icon-maneuvers.png'),
    wind: require('./img/icons/icon-wind.png'),
    error: require('./img/icons/icon-error.png'),
    mark: require('./img/icons/icon-mark.png'),
    competitor: require('./img/icons/icon-account-filled.png'),
  },
  animations: {
    waveLoadingIndicator: require('./img/animations/wave_loading.json'),
    waveLoadingIndicatorGif: require('./img/animations/wave_loading.gif'),
    waveLoadingIndicatorBackground: require('./img/animations/wave_loading_background.png'),
  },
  courseConfig: {
    roundingDirectionLeft: require('./img/icons/icon-rounding-direction-left.png'),
    roundingDirectionRight: require('./img/icons/icon-rounding-direction-right.png'),
    arrowUp: require('./img/icons/arrow-up.png'),
    tracker: require('./img/icons/icon-tracker.png'),
    location: require('./img/icons/icon-location.png'),
    gatePassing: require('./img/icons/gate-passing.png'),
    linePassing: require('./img/icons/line-passing.png'),
    deleteIcon: require('./img/icons/delete-icon.png'),
    gateIcon: require('./img/icons/gate-icon.png'),
    markPortIcon: require('./img/icons/mark-port-icon.png'),
    markStarboardIcon: require('./img/icons/mark-starboard-icon.png')
  },
  events: {
    placeholder_event_pic: require('./img/events/placeholder_eventlist.png'),
    archive: require('./img/icons/icon-event-archive.png'),
  },
  markInventory: {
    markIcon: require('./img/icons/mark-icon-small.png'),
  },
  account: {
    account_placeholder: require('./img/account/account_placeholder.png'),
    account_gradient: require('./img/account/gradient.png'),
  },
}
