export const Welcome = 'Welcome'
export const QRScanner = 'QRScanner'
export const CheckIn = 'CheckIn'
export const CheckInNavigator = 'CheckInNavigator'
export const RegattaDetail = 'RegattaDetail'
export const AppSettings = 'AppSettings'
export const Tracking = 'Tracking'
