declare module '@assets/*'

declare module 'string-format'
declare module 'react-native-background-geolocation'
declare module 'react-native-offline'
declare module 'react-native-extended-stylesheet'
declare module '@expo/react-native-action-sheet'
declare module 'react-native-background-timer'
declare module 'react-native-status-bar-height'
declare module 'react-native-qrcode-scanner'
declare module 'react-native-hyperlink'
declare module 'react-native-keep-awake'
declare module 'react-native-timer'
declare module 'moment/*'
declare module 'react-native-i18n'
